### ISSUE TITLE
Make uploaded file publicly accessible by setting ACL=public

### ISSUE THREAD

**Issue by pkcs12** [JustinM1/VaporS3Signer#1]
File upload works just perfect, but whenever I try to download file from iOS client I'm getting `AccessDenied`. Somebody told me that there should be ACL => 'public' key-value set somewhere in request body, so S3 will know that this file should be accessible without authentication.
Please tell me how can I add additional parameters for uploaded file

**Comment by pkcs12** [comment]
Answering my own question:
Need to include header "x-amz-acl" with value from the list:
`private` | `public-read` | `public-read-write` | `aws-exec-read` | `authenticated-read` | `bucket-owner-read` | `bucket-owner-full-control`

By default its `private`.

For me works ["x-amz-acl": "public-read"]

**Comment by JustinM1** [comment]
Glad to see you worked it out
