### ISSUE TITLE
X-Amz-Credential parameter; the region 'eu-west-1' is wrong; expecting 'eu-west-2'

### ISSUE THREAD

**Issue by TempaGoGo** [JustinM1/VaporS3Signer#5]
Hello,

Thank you for writing this Vapor provider. However, I am getting the above error for my request.

X-Amz-Credential parameter; the region 'eu-west-1' is wrong; expecting 'eu-west-2'

However, the Region object doesn't have an enum value for this, so I can't set the right config.

I could well be doing something wrong!

Phil

**Comment by JustinM1** [comment]
That is one of the newer regions available, it has been added along with CA Central region. Thanks for the heads up, Phil.
