### ISSUE TITLE
Accessing s3Signer, throws an error every time...

### ISSUE THREAD

**Issue by pascalfriedrich** [JustinM1/VaporS3Signer#7]
... even without payload.

```
v1.post("employeeImage", ":id") { req in
            guard let objectid = req.parameters["id"]?.string else {
                throw Abort.badRequest
            }

            let urlString = "https://" + Region.euCentral1.host.appending("yapa/\(objectid)")
            print(req.formData?["image"]?.part.body)
            guard let payload = req.body.bytes,
                let headers = try self.drop.s3Signer?.authHeaderV4(
                    httpMethod: .put,
                    urlString: urlString,
                    payload: Payload.bytes(payload)) else { throw Abort.serverError }
            
            let vaporHeaders = headers.vaporHeaders
            
            let resp = try self.drop.client.put(
                urlString, query: [:], vaporHeaders,
                Body(payload))
            
            return resp
        }
```

**Comment by JustinM1** [comment]
What is the error that is being thrown?

**Comment by pascalfriedrich** [comment]
guard falls into Abort.serverError.
Maybe it‘s important to say i‘m using vapor 2.

**Comment by JustinM1** [comment]
And you checked to make sure ‘body.bytes’ isn’t nil?

**Comment by pascalfriedrich** [comment]
`updatedHeaders["Authorization"] = try generateAuthHeader(
				httpMethod: httpMethod,
				url: url,
				headers: updatedHeaders,
				bodyDigest: bodyDigest,
				dates: dates)
			`

I played a little bit around and this code failes.

**Comment by pascalfriedrich** [comment]
Yes, body.bites is not nil. Vapor is be able to save the files locally (HDD) and hashing is working.

**Comment by pascalfriedrich** [comment]
Oh no, found the problem: the framework is not added to the storage.

**Comment by JustinM1** [comment]
Are you using more than one Droplet? Are you adding the provider to your droplets config?
